version: 1.0.{build}
before_build:
- ps: .\set-version.ps1
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: y9noy4A42pp9KcZurIOcCXDBkFu1GKbPFQUtPn74FKeDQwMHX3M31U1NpNn6caV6
  artifact: /.*\.nupkg/